name: Build IPK Package sing-box

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
          gettext git libncurses-dev libssl-dev python3-setuptools rsync unzip zlib1g-dev \
          file wget libelf-dev ccache zstd

    - name: Cache OpenWrt SDK build artifacts
      id: cache-sdk
      uses: actions/cache@v3
      with:
        path: openwrt-sdk
        key: Linux-openwrt-sdk-${{ hashFiles('openwrt-sdk/.config') }}
        restore-keys: |
          Linux-openwrt-sdk-
          Linux-

    - name: Clone OpenWrt SDK
      if: steps.cache-sdk.outputs.cache-hit != 'true'
      run: |
        export SDK_URL="https://downloads.openwrt.org/releases/24.10.2/targets/armsr/armv8/openwrt-sdk-24.10.2-armsr-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst"
        wget $SDK_URL
        tar -I zstd -xvf openwrt-sdk-*.tar.zst -C . && sync && rm -f openwrt-sdk-*.tar.zst
        mv -f openwrt-sdk-* openwrt-sdk

    - name: Copy package into SDK
      run: |
        cp -r ./sing-box ./openwrt-sdk/package/
    - name: Patch Go to 1.25
      run: |
        cd openwrt-sdk/feeds/packages/lang/golang
        sed -i 's/GO_VERSION_MAJOR_MINOR:=1.23/GO_VERSION_MAJOR_MINOR:=1.24/' Makefile
        sed -i 's/GO_VERSION_PATCH:=.*/GO_VERSION_PATCH:=5/' Makefile
        head -n 20 Makefile
    
    - name: Update feeds and defconfig only if needed
      run: |
        cd openwrt-sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        rm -rf feeds/packages/net/sing-box
        echo -e "CONFIG_PACKAGE_sing-box=m" >> .config
        make defconfig

    - name: Build package
      run: |
        cd openwrt-sdk
        make package/golang/host/clean
        make package/golang/host/compile -j$(nproc)
        make package/sing-box/clean
        make package/sing-box/compile V=s

    - name: Upload compiled IPK
      uses: actions/upload-artifact@v4
      with:
        name: sing-box
        path: |
          openwrt-sdk/bin/packages/*/*/sing-box_*.ipk
          
