name: Build IPK Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
          gettext git libncurses-dev libssl-dev python3-setuptools rsync unzip zlib1g-dev \
          file wget libelf-dev ccache zstd

    - name: Clone OpenWrt SDK
      run: |
        export SDK_URL="openwrt-sdk-24.10.1-armsr-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst"
        wget $SDK_URL
        tar -I zstd -xvf openwrt-sdk-*.tar.xz
        mv openwrt-sdk-* openwrt-sdk

    - name: Copy package into SDK
      run: |
        cp -r ./luci-app-tinyfm ./openwrt-sdk/package/

    - name: Build package
      run: |
        cd openwrt-sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make package/luci-app-tinyfm/compile V=s

    - name: Upload compiled IPK
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-tinyfm
        path: |
          openwrt-sdk/bin/packages/*/*/*.ipk
          
